In [73]:
#Jake Castillo (Mon,10,2020)
#1 [3,4,5,6],[0,1,0,1],[3,7,5,13] are they in the same plane?
import numpy as np
import numpy.random as npr

# For plotting

import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

#3+4+5+6 = 18
#0+1+0+1 = 2
#3+7+5+13 = 28
#Assumption: They do not exist in the same plane. The system is inconsistent.
#Attempted elimination

A = np.array([[3,4,5,6],[0,1,0,1]]).T
b = np.array([3,7,5,13]).reshape(4,1)
print('A,b')
print(A, '\n', b)
print('\n')
E1 = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[-2,0,0,1]])

A1 = E1 @ A
b1 = E1 @ b
print('A1,b1')
print(A1,'\n',b1)
print('\n')
E2 = np.array([[1,0,0,0],[0,1,0,0],[-5/3,0,1,0],[0,0,0,1]])

A2 = E2 @ A1
b2 = E2 @ b1
print('A2,b2')
print(A2,'\n',b2)
print('\n')

E3 = np.array([[1,0,0,0],[-4/3,1,0,0],[0,0,1,0],[0,0,0,0]])

A3 = E3 @ A2
b3 = E3 @ b2
print('A3,b3')
print(A3,'\n',b3)

A,b
[[3 0]
 [4 1]
 [5 0]
 [6 1]] 
 [[ 3]
 [ 7]
 [ 5]
 [13]]


A1,b1
[[3 0]
 [4 1]
 [5 0]
 [0 1]] 
 [[3]
 [7]
 [5]
 [7]]


A2,b2
[[3. 0.]
 [4. 1.]
 [0. 0.]
 [0. 1.]] 
 [[3.]
 [7.]
 [0.]
 [7.]]


A3,b3
[[3. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]] 
 [[3.]
 [3.]
 [0.]
 [0.]]


In [ ]:
#W1(3) = 3
#W2(1) = 3

In [74]:
#2 Find the vector closest to A = b
from sklearn.linear_model import LinearRegression

reg = LinearRegression(fit_intercept=True).fit(A, b)
print('The coefficients from scikit-learn are ', reg.coef_)
print('\n')
#coefficients are [[2. 4.]]
print(reg.predict(A))

print('\n')
err = reg.predict(A)-b
print(err.T @ err)

The coefficients from scikit-learn are  [[2. 4.]]


[[ 2.]
 [ 8.]
 [ 6.]
 [12.]]


[[4.]]
